struct WordsBank {
    static var shared = WordsBank()
    
    var easyWordsList = [
        "Feijão",
        "Irmão",
        "Almoçar",
        "Viajar",
        "Falar",
        "Rua",
        "Brasil",
        "Bolsonaro",
        "Arena",
        "Boca",
        "Presente",
        "Passado",
        "Futuro",
        "Produz",
        "Andar",
        "Pelé",
        "Engraçado",
        "Cobertor",
        "Amor",
        "Bebida",
        "Teto",
        "Verão",
        "Paixão",
        "Ilusão",
        "União",
        "Contramão",
        "Atriz",
        "Giz",
        "Nariz",
        "Juiz",
        "Treta",
        "Programação",
        "Toca",
        "Cadê",
        "Bebê",
        "Chuva",
        "Poluição",
        "Fogo"
    ]
    
    var mediumWordsList = [
        "Plateia",
        "Corona",
        "Astronauta",
        "Feijoada",
        "Mamonas",
        "Romário",
        "Atual",
        "Comédia",
        "Cigarro",
        "Segundo",
        "Julgamento",
        "Sentença",
        "Internet",
        "Site",
        "Skate",
        "Yoga",
        "Girafa",
        "Geladeira",
        "Sol",
        "Água",
    ]
    
    var hardWordsList = [
        "Paralelepípedo",
        "Morcego",
        "Vírus",
        "Cogumelo",
        "Naruto",
        "Submarino",
        "Noz",
        "Áudio",
        "Complexo",
        "Dados",
        "Código",
        "Da Vinci",
        "Rinoceronte",
        "Hibisco",
        "Abduzir",
        "Balbúrdia",
        "Ardiloso",
        "Dilúvio",
        "Frenético",
        "Idiossincrasia",
        "Incólume",
        "Tóxico"
    ]
}
